# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo.png"
    high_res_favicon: "/img/logo.png"
    apple_touch_icon: "/img/logo.png"
    keywords: maple

Intro:
    name: Feng Ting
    slogan: "再拥挤的繁华，枫停都会让你的爱车找到家！"
    logo: "/img/logo.png"

Nav:
    Home_name: 枫停App
    is_use_categories : false 
    categories_name: 成为车位主
    is_use_archives : false
    archives_name: 
    icon:
        github: 
            use: true
            link: https://github.com/d-ouyang
        Twitter:
            use: false
            link: 
        Facebook:
            use: false
            link: 
        Instagram:
            use: false
            link:
    pages:
        成为车位主:
            link: "/being/"
        关于我们:
           link: "/gallery/"
        物业合作:
           link: "/about/"

MainFirst:
    name: Mapleparking
    description: Welcome to Feng Ting
    pic_url: /images/me.jpg
    goto_ulr: "/"

Gallery :
    title: Mapleparking
    description: 让心情去旅行,枫停 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: disqus_click
    shortname: http-miccall-tech 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
